# Generated by Django 3.2.15 on 2023-08-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_auto_20230804_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Ne', 'Новый заказ'), ('Pr', 'Обработанный'), ('Fi', 'Завершенный')], db_index=True, default='Ne', max_length=2, verbose_name='статус'),
        ),
    ]
