# Generated by Django 3.2.15 on 2023-08-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_auto_20230804_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_new_order',
            field=models.BooleanField(default=True, verbose_name='Новый заказ'),
        ),
    ]
