# Generated by Django 3.2.15 on 2023-08-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocodercache', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='update_ts',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
